{
  "name" : "Continuous Integration",
  "on" : {
    "push" : {
      "paths" : [
        "**.yml",
        "**.sh",
        "**.tjs",
        "**.ks",
        "**.ksc",
        "**.dic",
        "**.arr",
        "**.png",
        "**.webp",
        "**.tlg",
        "**.ogg",
        "**.opus"
      ]
    },
    "pull_request" : {
      "paths" : [
        "**.yml",
        "**.sh",
        "**.tjs",
        "**.ks",
        "**.ksc",
        "**.dic",
        "**.arr",
        "**.png",
        "**.webp",
        "**.tlg",
        "**.ogg",
        "**.opus"
      ]
    }
  },
  "jobs" : {
    "build-xp3" : {
      "runs-on" : "ubuntu-20.04",
      "timeout-minutes" : 20,
      "steps" : [
        {
          "name" : "Checkout the repository",
          "uses" : "actions/checkout@v2",
          "with" : {
            "submodules" : "recursive"
          }
        },
        {
          "name" : "Update apt repository",
          "run" : "sudo apt-get update"
        },
        {
          "name" : "Install p7zip",
          "run" : "sudo apt-get install -y p7zip"
        },
        {
          "name" : "Download krkrrel",
          "run" : "curl -LOC - https://github.com/krkrsdl2/krkrrel-ng/releases/download/latest/krkrrel-ubuntu.zip"
        },
        {
          "name" : "Extract krkrrel",
          "run" : "7z x -okrkrrel-tmp krkrrel-ubuntu.zip"
        },
        {
          "name" : "Append krkrrel to path",
          "run" : "echo \"$(realpath krkrrel-tmp)/krkrrel-ubuntu\" >> $GITHUB_PATH"
        },
        {
          "name" : "Change permissions for krkrrel",
          "run" : "chmod +x krkrrel-tmp/krkrrel-ubuntu/krkrrel"
        },
        {
          "name" : "Do build",
          "run" : "bash build.sh"
        },
        {
          "uses" : "actions/upload-artifact@v4",
          "with" : {
            "name" : "krkrsdl2-kag3-demo-xp3",
            "path" : "data.xp3"
          }
        }
      ]
    },
    "create-release" : {
      "needs" : ["build-xp3"],
      "runs-on" : "ubuntu-20.04",
      "timeout-minutes" : 20,
      "if" : "github.ref == 'refs/heads/main'",
      "steps" : [
        {
          "name" : "Download xp3 artifact",
          "uses" : "actions/download-artifact@v4",
          "with" : {
            "name" : "krkrsdl2-kag3-demo-xp3"
          }
        },
        {
          "name" : "Create prerelease",
          "if" : "github.ref == 'refs/heads/main'",
          "uses" : "marvinpinto/action-automatic-releases@latest",
          "with" : {
            "repo_token" : "${{ secrets.GITHUB_TOKEN }}",
            "prerelease" : "true",
            "automatic_release_tag" : "latest",
            "title" : "Latest development builds",
            "files" : "krkrsdl2-kag3-demo-xp3/data.xp3"
          }
        }
      ]
    }
  }
}
